version: '3.4'
 
services:
  redis:
    image: "redis"
     ports:
       - "6379:6379"
  VikWeatherServiceApi:
    image: VikWeatherServiceApi.api
     restart: always
     ports:
       - 5001:80
    build:
       context: .
       dockerfile: Dockerfile
     depends_on:
       - "redis"