//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crexi.WeatherForecast.Dao.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WeatherForecastDb : DbContext
    {
        public WeatherForecastDb()
            : base("name=WeatherForecastDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SaveUserAccessHistory(string user_ip_address, Nullable<System.DateTime> access_date, string user_agent)
        {
            var user_ip_addressParameter = user_ip_address != null ?
                new ObjectParameter("user_ip_address", user_ip_address) :
                new ObjectParameter("user_ip_address", typeof(string));
    
            var access_dateParameter = access_date.HasValue ?
                new ObjectParameter("access_date", access_date) :
                new ObjectParameter("access_date", typeof(System.DateTime));
    
            var user_agentParameter = user_agent != null ?
                new ObjectParameter("user_agent", user_agent) :
                new ObjectParameter("user_agent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveUserAccessHistory", user_ip_addressParameter, access_dateParameter, user_agentParameter);
        }
    }
}
